kind: pipeline
type: docker
name: default

steps:
- name: test
  image: localhost:5000/golang-fuseki:latest
  commands:
  - /opt/fuseki/fuseki-server --mem --port=3030 /tmp &
  - sleep 10s
  - go test ./...
  - go build
- name: package
  image: localhost:5000/golang-docker:latest
  commands:
    - docker build -t localhost:5000/devprivops:latest .
    - docker push localhost:5000/devprivops:latest
trigger:
  event:
    - push
