# O
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: localhost:5000/golang-fuseki:latest
  commands:
  - /opt/fuseki/fuseki-server --mem --port=3030 /tmp &
  - sleep 3s
  - go test ./...
- name: package
  image: plugins/docker
  settings:
    registry: 192.168.56.1:5000
    repo: 192.168.56.1:5000/devprivops
    tags: latest
    dockerfile: Dockerfile
    insecure: true
trigger:
  event:
    - push
