kind: pipeline
type: docker
name: default

steps:
- name: test
  image: registry:5000/golang-fuseki:latest
  commands:
  - go test ./...
  - go build

trigger:
  #branch:
  #  - master
  event:
    - push
