kind: pipeline
type: docker
name: default

steps:
- name: test
  image: localhost:5000/golang-fuseki:latest
  commands:
  - /opt/fuseki/fuseki-server --mem --port=3030 /tmp &
  - sleep 3s
  - go test ./... -cover
  - sh integration_tests.sh
- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
      sonar_host: http://rpi:9001
      sonar_token: sqp_c91d344d2ce4252fa9db4301c94b94084cead69d
- name: package
  image: plugins/docker
  settings:
    registry: 192.168.56.1:5000
    repo: 192.168.56.1:5000/devprivops
    tags: latest
    dockerfile: Dockerfile
    insecure: true
trigger:
  event:
    - push
