kind: pipeline
type: docker
name: default

steps:
- name: test
  image: localhost:5000/golang-fuseki:latest
  commands:
  - sleep 20s
  - go test ./...
  - go build

trigger:
  #branch:
  #  - master
  event:
    - push
