kind: pipeline
type: docker
name: default

steps:
- name: test
  image: localhost:5000/golang-fuseki:latest
  commands:
  - /opt/fuseki/fuseki-server --mem --port=3030 /tmp &
  - sleep 10s
#  - ps aux
#  - curl localhost:3030
  - go test ./...
  - go build

trigger:
  event:
    - push
