# yaml-language-server: $schema=../../../schema/schemas/requirement-schema.json

- use case: As an AuthenticatedUser I want to share Documents with other AuthenticatedUsers so that they can download them
  is misuse case: false
  clearence level: 0
  groups: ["all"]
  requirements:
    - title: AuthenticatedUsers must be able to see Documents and PrivDocuments shared with them
      description: An authenticated user, when given a document link, must be able to authenticate and get the document.
      query: requirements/auth_user_get_doc.rq
      clearence level: 0
      groups: ["all"]
