# yaml-language-server: $schema=../../../schema/schemas/requirement-schema.json

- use case: As an AuthenticatedUser I want to share Documents with other AuthenticatedUsers so that they can download them
  is misuse case: false
  clearence level: 0
  groups: ["all"]
  requirements:
    - title: AuthenticatedUsers must be able to see Documents and PrivDocuments shared with them
      description: An authenticated user, when given a document link, must be able to authenticate and get the document.
      query: requirements/auth_user_get_doc.rq
      clearence level: 0
      groups: ["all"]
- use case: As an UnauthenticatedUser I want to view Documents so that I can recieve Documents without the hassle of having an account  
  is misuse case: false
  clearence level: 0
  groups: ["all"]
  requirements:
    - title: UnauthenticatedUsers must be able to see Documents
      description: An unauthenticated user, when given a document link, must be able to get the document without authentication.
      query: requirements/unauth_user_get_doc.rq
      clearence level: 0
      groups: ["all"]

# Misuse cases

- use case: As an AuthenticatedUser I want to spam the system with files so that it runs out of storage faster
  is misuse case: true
  clearence level: 0
  groups: ["all"]
  requirements:
    - title: AuthenticatedUsers must be able to post files at a rate higher than the one supported by the system
      description: An AuthenticatedUser, with intent to deny service to everyone else by filling storage needlessly, must be able to send files at a high rate
      query: requirements/auth_user_spam.rq
      clearence level: 0
      groups: ["all"]
